### PR TITLE
Make the example in README.md runnable

### PR DESCRIPTION
**Pull request by wangkuiyi**
After adding these two lines, I could copy-n-paste this example into a Python source file, say `/tmp/a.py`, and run it.

```
18:01 $ python /tmp/a.py
module @trivial_kernel {
  "ml_program.global"() {is_mutable, sym_name = "_params$0", sym_visibility = "private", type = tensor<3x4xf32>, value = dense<4.000000e+00> : tensor<3x4xf32>} : () -> ()
  "ml_program.global"() {is_mutable, sym_name = "_params$1", sym_visibility = "private", type = tensor<3x4xf32>, value = dense<1.000000e+00> : tensor<3x4xf32>} : () -> ()
  func.func @get_params() -> (tensor<3x4xf32>, tensor<3x4xf32>) {
    %0 = "ml_program.global_load"() {global = @_params$0} : () -> tensor<3x4xf32>
    %1 = "ml_program.global_load"() {global = @_params$1} : () -> tensor<3x4xf32>
    return %0, %1 : tensor<3x4xf32>, tensor<3x4xf32>
  }
  func.func @run(%arg0: tensor<3x4xf32>) -> tensor<3x4xf32> {
    %0 = "ml_program.global_load"() {global = @_params$0} : () -> tensor<3x4xf32>
    %1 = "ml_program.global_load"() {global = @_params$1} : () -> tensor<3x4xf32>
    %2 = call @jit__linear$main(%arg0, %0, %1) : (tensor<3x4xf32>, tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xf32>
    "ml_program.global_store"(%2) {global = @_params$0} : (tensor<3x4xf32>) -> ()
    return %2 : tensor<3x4xf32>
  }
  func.func private @jit__linear$main(%arg0: tensor<3x4xf32> {mhlo.sharding = ""}, %arg1: tensor<3x4xf32> {mhlo.sharding = ""}, %arg2: tensor<3x4xf32> {mhlo.sharding = ""}) -> tensor<3x4xf32> {
    %0 = stablehlo.multiply %arg0, %arg1 : tensor<3x4xf32>
    %1 = stablehlo.add %0, %arg2 : tensor<3x4xf32>
    return %1 : tensor<3x4xf32>
  }
  func.func @set_params(%arg0: tensor<3x4xf32>, %arg1: tensor<3x4xf32>) {
    "ml_program.global_store"(%arg0) {global = @_params$0} : (tensor<3x4xf32>) -> ()
    "ml_program.global_store"(%arg1) {global = @_params$1} : (tensor<3x4xf32>) -> ()
    return
  }
}

Traceback (most recent call last):
  File "/tmp/a.py", line 95, in <module>
    print("Initial params:", m.get_params())
  File "/Users/y/w/iree-jax/iree/jax/program_api.py", line 284, in _uncallable_public_export
    raise RuntimeError(f"Calls to exported functions not yet supported")
RuntimeError: Calls to exported functions not yet supported
```

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]

**Comment by wangkuiyi** [comment]
I am looking for the process of trace a JAX program and compile it. So I tried to compile the above MLIR program using `iree-compile` with the following command:

```bash
python /tmp/a.py 2>/dev/null | \
   ~/w/iree-build/install/bin/iree-compile --iree-hal-target-backends=vmvx -
```

Unfortunately, it failed with the following error messages.
```
<stdin>:17:10: error: failed to legalize operation 'stablehlo.multiply' that was explicitly marked illegal
    %0 = stablehlo.multiply %arg0, %arg1 : tensor<3x4xf32>
         ^
<stdin>:9:3: note: called from
  func.func @run(%arg0: tensor<3x4xf32>) -> tensor<3x4xf32> {
  ^
<stdin>:17:10: note: see current operation: %53 = "stablehlo.multiply"(%38, %52) : (tensor<3x4xf32>, tensor<3x4xf32>) -> tensor<3x4xf32>
    %0 = stablehlo.multiply %arg0, %arg1 : tensor<3x4xf32>
         ^
```

Is this expected? Am I doing something non-sense?

**Comment by stellaraccident** [comment]
If compiling hlo manually like this, add --iree-input-type=mhlo

**Comment by jpienaar** [comment]
I think we should add a simple heuristic for input type or make it required rather than current default, well or make it so that we don't need it, we've had a couple of reports here and I think we could go far with a simple heuristic or two ( @dellis23 for visibility on user journey).

**Comment by ScottTodd** [comment]
> I think we should add a simple heuristic for input type or make it required rather than current default, well or make it so that we don't need it, we've had a couple of reports here and I think we could go far with a simple heuristic or two ( @dellis23 for visibility on user journey).

https://github.com/iree-org/iree/issues/10297

**Pull request merged**
