### PR TITLE
IR value tracing of Mapping and Iterable interfaces

### PR DESCRIPTION
**Pull request by sogartar**
Makes the tracing of values more general.
Instead of only handling dict, list, tuple.
This enables handling of Flax's FrozenDict.

### CODE REVIEW

**Comment by jpienaar** [comment]
Does this flatten all pytrees using something like depth/breadth-first iteration?

**Comment by sogartar** [comment]
It uses sorted keys https://github.com/tensorflow/tensorflow/blob/4139a2ada21479f923a850bf2708dfe077a22254/tensorflow/compiler/xla/python/pytree.cc#L209
With `<` (less than) comparisson. In the case of strings it uses lexicographical ordering.

With this change anything that implements the `Mapping` interface will be treated as a `dict`.
Everything else that implements the `Iterable` interface will be treated as a `list`.

**Comment by sogartar** [comment]
This can be done in a different way as `tree_flatten` has some facilities for custom type handling.
https://github.com/tensorflow/tensorflow/blob/4139a2ada21479f923a850bf2708dfe077a22254/tensorflow/compiler/xla/python/pytree.cc#L217
They need to be registered first, but it seems the registry is global, which will affect all call sites. It will avoid the creation of the temporary `dict`/`list`.
`tree_flatten` also accepts the predicate `is_leaf`.

**Comment by dellis23** [comment]
Can you comment the intent of the new conversions (perhaps mentioning flax's frozendict, if that's the primary reason for doing this)? Is there a small simple test you can add that would have failed before for frozendict that doesn't now? Similarly for the other path, can we test the list conversion too?

**Review by dellis23 — CHANGES_REQUESTED** [review]
Can you comment the intent of the new conversions (perhaps mentioning flax's frozendict, if that's the primary reason for doing this)? Is there a small simple test you can add that would have failed before for frozendict that doesn't now? Similarly for the other path, can we test the list conversion too?

**Comment by sogartar** [comment]
@dellis23, I added a test the uses Flax's FrozenDict that goes through the `collections.abc.Mapping` path.

Regarding the `collections.abc.Iterable` path. I was unable to find a type to test with that is not a `list` or a `tuple` and JAX is happy to accept. I tried with `collections.deque`. I can remove this path.
The benefit of that will be that if in the future there is a new array like value type, it will return a more sane error of not supporting this type. In the other case the array type will get treated as a list of values and you will probably get cryptic shape or structure mismatch errors down the line.
The benefit of leaving it is that if a new list-like type is encountered in the future it will support it.

**Comment by dellis23** [comment]
Thanks! I lean toward removing the path that isn't used right now, but I don't feel strongly. Up to you.

**Review by dellis23 — APPROVED** [review]

**Review by dellis23 — APPROVED** [review]
Thanks!

**Comment by dellis23** [comment]
Would you like me to merge? Just want to make sure before I do so.

**Pull request merged**
